### PR TITLE
added process time by minute algorithm

### PR DESCRIPTION
**Pull request by Adir111**
needed for work here:
https://github.com/kube-HPC/hkube/pull/2009

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/examples/11)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
Also print with minutes changes from odd to even

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/examples/11#-:-OASOz3jAt4fNvTywme7:b-psexfb)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Adir111)

___
*[`streaming-time/statelessGetSendAccordingToMinuteTime.py` line 12 at r2](https://reviewable.io/reviews/kube-HPC/examples/11#-OASOjNnD9O5mATFTgkn:-OASOjNnD9O5mATFTgko:bxp3gx2) ([raw file](https://github.com/kube-HPC/examples/blob/9bd1d435f009c222237f4f58e5eb80ae522fedca/streaming-time/statelessGetSendAccordingToMinuteTime.py#L12)):*
> ```Python
> def start(args, hkube_api):
>     current_minute = datetime.now().minute
>     process_time = 1 if current_minute % 2 == 0 else 0.1
> ```

No need for this line, right?



_Code quote:_
```Python
    process_time = 1 if current_minute % 2 == 0 else 0.1
```

**Review by Adir111 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/examples/11)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Adir111 and @golanha)

___
*[`streaming-time/statelessGetSendAccordingToMinuteTime.py` line 12 at r2](https://reviewable.io/reviews/kube-HPC/examples/11#-OASOjNnD9O5mATFTgkn:-OASRas75RMjdh5opSiD:b-58so7g) ([raw file](https://github.com/kube-HPC/examples/blob/9bd1d435f009c222237f4f58e5eb80ae522fedca/streaming-time/statelessGetSendAccordingToMinuteTime.py#L12)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

No need for this line, right?
</blockquote></details>

needed.

**Review by Adir111 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/examples/11#-:-OAYCe9UDJ9CAu8z36O0:bb6un1j)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Adir111 and @golanha)

**Comment by golanha** [comment]
*[`streaming-time/statelessGetSendByIntervalTime.py` line 38 at r4](https://reviewable.io/reviews/kube-HPC/examples/11#-OAvUkku0YSyYmbZI0nO:-OAvUkku0YSyYmbZI0nP:b-jgs7ls) ([raw file](https://github.com/kube-HPC/examples/blob/d53e25540e4920e093e691c0d41b0b5cd48bbe7f/streaming-time/statelessGetSendByIntervalTime.py#L38)):*
> ```Python
>     if change_occurred:
>         print(f"Process time is set to: {process_time}")
> ```

lastValue is not global and is not kept between invokations.

You don't really need the cuurentlyFirst variable.
You can make lastValue global, and have it keep the last module result, and thats it.
Jast initialize the lastValue with the oposite of currModelo.

**Review by Adir111 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/examples/11)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Adir111 and @golanha)

___
*[`streaming-time/statelessGetSendByIntervalTime.py` line 38 at r4](https://reviewable.io/reviews/kube-HPC/examples/11#-OAvUkku0YSyYmbZI0nO:-OAvZ4wh-F0DBN_4VHUA:btdo21o) ([raw file](https://github.com/kube-HPC/examples/blob/d53e25540e4920e093e691c0d41b0b5cd48bbe7f/streaming-time/statelessGetSendByIntervalTime.py#L38)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

*  Just  :-)
</blockquote></details>

Code changed :-)

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/examples/11)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)

**Pull request merged**
